### ISSUE TITLE
Wrong popup positioning

### ISSUE THREAD

**Issue by zoryana94** [ryank109/react-redux-popup#25]
Hi Ryan!
I use your popup for the app. It's positioned properly on the biggers screen resolutions.
When there is the small screen resolution, It's shown not where it should be.
![123789](https://user-images.githubusercontent.com/21179657/36691107-ee92b438-1b3c-11e8-844f-586992f7d9ac.png)
I'd be thankful if you look at it... maybe, you know some workarounds

**Comment by ryank109** [comment]
Hi, thanks for trying out my popup!
Do you have a scroll in your window?  I think I might have positioning issue when the source element is scrolled from the top. I'll take a look.

**Comment by ryank109** [comment]
It seems like if you let the entire window scroll, that's when the positioning gets out of place.  I have an example for scrolling, but in that case, it was for scrolling within a div content.  I'll see if I can make it work for both.  Thanks!

Also, if you have window scrolling, you probably don't have to dispatch `refreshPopupPosition` action on scroll event of the window.  You probably aren't doing that, but just noting the things I found. :)

**Comment by ryank109** [comment]
@zoryana94
I have pushed up the fix on version 3.0.2.  Please try out and let me know if that fixed your problem.  Thanks!

**Comment by zoryana94** [comment]
Thanks a lot! Yeah... I have a scrollbar... I'll try

**Comment by zoryana94** [comment]
Hi! I've tried to rewrite the components in order to make the app work with the updated react-redux-popup version. But I've just read the following:
```
React v16 only, because it leverages its Portal API)
For React v15.5 - use version 2.x
```
We use the 15.5.4 react version.
Could you, please, fix the issue for the older version of the rfeact-redux-popup also?

**Comment by ryank109** [comment]
@zoryana94 ok, version 2.1.7 is updated with scroll fix.  Please try and let me know if that works.  Thanks!

**Comment by zoryana94** [comment]
Thanks a lot, Ryan!!!! It works!!! I'm really very thankful!! You're cool!!!)
