### ISSUE TITLE
Wrong popup positioning in IE

### ISSUE THREAD

**Issue by zoryana94** [ryank109/react-redux-popup#27]
Hi!!!)

After updating the version of the react-redux-popup to 2.7.1 the popup positioning looks incorrect in IE.
![ie](https://user-images.githubusercontent.com/21179657/37102243-16ed345e-2230-11e8-8f02-8cc7a796a0dc.PNG)
I've researched. Maybe, the reason is in the following:

```
there's an issue of the plugin not being able to properly position the zoom pane on IE 11, because the computation required to assign the top and left values returns NaN.

This can be fixed using window.pageXOffset and window.pageYOffset instead of window.scrollX and window.scrollY. As you can see here, using window.pageXOffset is better for cross-browser compat.
```

See: https://github.com/imgix/drift/issues/33

**Comment by zoryana94** [comment]
I've added the necessary changes locally. And It works. Could you, please, change the scrollX and scrollY properties to pageXOffset and pageYOffset respectively, or just share the access to your repository cause I don't have the permission.

**Comment by ryank109** [comment]
Ok, thanks.  Updated on version [2.1.8](https://github.com/ryank109/react-redux-popup/releases/tag/2.1.8) and version [3.0.3](https://github.com/ryank109/react-redux-popup/releases/tag/3.0.3)

**Comment by zoryana94** [comment]
Thanks a lot!!!)
